### ISSUE TITLE
Phase 7: Polish Readme & Repository

### ISSUE THREAD

**Issue by pr-124** [Yer1k/Song_Recommender#11]
# Polish Readme & Repository

## Objective:
Polish the Readme file and repository for our project to ensure that it is well-documented, organized, and easy to use for potential users. Review the project structure, documentation, and code quality, and make any necessary updates to improve the overall quality of the repository.

**Tasks**

- [x] Review the project structure.
- [x] Update the Readme file with clear and concise instructions on how to use the project. 
- [x] Ensure that potential new users can run our library/application without assistance. Provide necessary Documentation       for installation and usage.
- [x] Ensure  that all automated testing, code linting, and code coverage analysis is passing.
- [x] Double-check that the coding style for the project is consistent and follows best practices. 
- [x] Ensure that all milestones have been completed.

**Comment by 5ukhy21** [comment]
This can be closed as we have updated and finalized the README.
